


---
- name: Collect Info
  hosts: test_servers
  become: false

  tasks:
   - name: test connection
     ping:

   - name: Populate servic facts
     ansible.builtin.service_facts:

   - name: Print all available services
     debug:
       var: ansible_facts.services

- name: Add repo
  hosts: test_servers
  become: yes

  tasks:
  - name: Add yum repo
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


- name: install services
  hosts: test_servers
  become: yes

  tasks:
  - name: install Docker
    yum:
      name:
        - docker
        - mc
        - python
        - zip
      state: present
 
  - name: Start and enable autostart Docker
    service:
      name: docker
      state: started
      enabled: yes      

- name: Create directory (server2)
  hosts: server2
  become: yes

  tasks:
  - name: Create directory /ARCHIVE 
    ansible.builtin.file:
      path: /ARCHIVE
      state: directory
      mode: '0755'

- name: Create directory (server3)
  hosts: server3
  become: yes

  tasks:
  - name: Create directory /ARCHIVE
    ansible.builtin.file:
      path: /ARCHIVE
      state: directory
      mode: '0755'

- name: Touch file /ARCHIVE/test_file
  hosts: server2
  become: yes

  tasks:
  - name: Create test_files
    ansible.builtin.file:
      path: /ARCHIVE/test_file
      state: touch
     # mode: u=rw,g=wx;o=rwx

- name: Touch file /ARCHIVE/test_file
  hosts: server3
  become: yes
 
  tasks:
  - name: Create test_file
    ansible.builtin.file:
      path: /ARCHIVE/test_file
      state: touch
 

