---
- name: Collect Info
  hosts: test_servers
  become: false

  tasks:
   - name: test connection
     ping:

   - name: Populate servic facts
     ansible.builtin.service_facts:

   - name: Print all available services
     debug:
       var: ansible_facts.services

- name: Add repo
  hosts: test_servers
  become: yes

  tasks:
  - name: Add yum repo
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


- name: install services
  hosts: test_servers
  become: yes

  tasks:
  - name: install Docker
    yum:
      name: docker
      state: present

  - name: Install MC
    yum:
      name: mc
      state: present
      
  - name: install python
    yum:
      name: python
      state: present
      
  - name: install java
    yum:
      name: java
      state: present
      
  - name: install zip
    yum:
      name: zip
      state: present    

  - name: install PostgreSQL
    yum:
      name: postgresql-server
      state: present

  - name: Start and enable autostart Docker
    service:
      name: docker
      state: started
      enabled: yes      
