---
- name: Collect Info
  hosts: test_servers
  become: false

  tasks:
   - name: test connection
     ping:

   - name: Populate servic facts
     ansible.builtin.service_facts:

   - name: Print all available services
     debug:
       var: ansible_facts.services

- name: Add repo
  hosts: test_servers
  become: yes

  tasks:
  - name: Add yum repo
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


- name: install soft
  hosts: test_servers
  become: yes

  tasks:
  - name: install soft
    yum:
      name:
        - docker
        - mc
        - python
        - zip
        - ntpdate
      state: present
 
  - name: Start and enable autostart Docker
    service:
      name: docker
      state: started
      enabled: yes      


  - name: Create directory /ARCHIVE 
    ansible.builtin.file:
      path: /ARCHIVE
      state: directory
      mode: '0755'


  - name: Create test_files
    ansible.builtin.file:
      path: /ARCHIVE/test_file
      state: touch

- name: Set hostname for server2
  hosts: server2
  become: yes

  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
      name: ansible.slave

- name: Set hostname for server3
  hosts: server3
  become: yes

  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
      name: ansible.slave1


- name: Set hostame for server4
  hosts: server4
  become: yes
  
  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
      name: ansible.slave2

 
- name: shutdown servers
  hosts: all
  become: yes

  tasks:
  - name: Reboot after 60  seconds
    command: /sbin/shutdown -r 1
      
