---
- name: REBOOT
  hosts: test_servers
  become_method: sudo
  become_user: root

  tasks:
  - name: REBOOT AND WHAITING
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
      notify: Reboot host and wait for it to restart
