#!/bin/bash
#Программа вывода страницы с информацией о системе
TITLE="SysInfo Report for $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"
cat << _EOF_
<html>
<head>
<title> $TITLE </title>
</head>
<body>
<h1> $TITLE </h1>
<p> $TIME_STAMP </p>
</body>
</html>
_EOF_
