#!/bin/bash
#Программа вывода страницы с информацией о системе
TITLE="SysInfo Report for $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

report_free_ram () {
cat <<- _EOF_
	<h2>Free RAM</h2>
	<pre>$(free -h)</pre>
	_EOF_
return
}

report_uptime () {
cat <<- _EOF_
	<h2>System Uptime</h2>
	<pre>$(uptime)</pre>
	_EOF_
return
}
report_disk_space () {
cat <<- _EOF_
	<h2>Disk Space Utilization</h2>
	<pre>$(df -h)</pre>
	_EOF_
return
}
report_home_space () {
cat <<- _EOF_
	<h2>Home Space Utilization</h2>
	<pre>$(du -sh /home/*)</pre>
	_EOF_
return
}

cat << _EOF_
<html>
<head>
<title> $TITLE </title>
</head>
<body>
<h1> $TITLE </h1>
<p> $TIME_STAMP </p>
$(report_free_ram)
$(report_uptime)
$(report_disk_space)
$(report_home_space)
</body>
</html>
_EOF_
